CSect   Symbol  Value   LENGTH    Flags:
----------------------------------------
SUM             000000  002F0A
        FIRST   000000              R
        LOOP    00000A              R
        MYLIT   00001D              R
        COUNT   000021              R
        TABLE   000024              R
        TABLE2  001794              R
        TOTAL   002F04              R

LiteralTable
Name    Operand Address Length:
---------------------------------------
EOF     454F46  2F07    3
